### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by ericmjl** [gordonbrander/lettersmith_py#9]
This isn't really an issue, just a note left to say thank you for putting lettersmith_py out there.

I picked it up while trying to make a static site for my Obsidian notes. I've made two now, and I'm enjoying learning new things every time I look at your code. Esp. w.r.t. functional programming -- lenses are a neat way to think about the problem of mutating data structures using functions!

Anyways, please feel free to close the issue whenever. Nothing biggie. Just wanted to say hi and say thanks. :smile:.

Enjoy the Christmas/New Year season!

**Comment by gordonbrander** [comment]
☺️
